name: Publish Release to Sonatype
on:
  workflow_dispatch:
    inputs:
      next_version:
        description: "Version bump"
        required: true
        type: choice
        options:
          - major
          - minor
          - patch
      snapshot:
        description: "Is Snapshot"
        required: true
        type: boolean

jobs:
  publish:
    name: Publish to Maven Central
    uses: entur/gha-maven-central/.github/workflows/gradle-publish.yml@v1
    with:
      next_version: ${{ inputs.next_version }}
      snapshot: ${{ inputs.snapshot }}
    secrets: inherit