name: Publish Release to Sonatype
on:
  workflow_dispatch:
    inputs:
      next_version:
        description: "Version bump"
        required: false
        type: choice
        options:
          - major
          - minor
          - patch
        default: "minor"

jobs:
  publish:
    name: Publish Snapshot to Maven Central
    uses: entur/gha-maven-central/.github/workflows/gradle-publish.yml@v1
    with:
      next_version: ${{ inputs.next_version }}
    secrets: inherit